version: '{branch}.{build}'

pull_requests:
  do_not_increment_build_number: true

# Only on top of the master branch
branches:
  only:
  - master

environment:
  GRADLE_OPTS: '"-Dorg.gradle.daemon=false"'

# assemble the library
build_script:
- cmd: .\gradlew.bat assemble

# run the tests
test_script:
- cmd: .\gradlew.bat test
